general:
  batch_size: 2048 # Training
  learning_rate: 0.01 # Training
  loss_logging_frequency: 100 # Each N epoch we print and save the loss
  boundary_threshold: 0.5 # Decision boundary when converting continous model output to binary 
  inf_bench_query_size: 10000000 # 10M, size of query to speed benchmark inference with
  inf_bench_repitions: 1000 # Number of repitions to average speed benchmark 
  aa_scaling : 3 # Fcator of original query size at which we sample for anti-aliasing (2 = we sample the image at double resolution and downsample to original size)
  inf_benchmark : False # Flag for infernece benchmarking or not, as this takes much extra time to run without always being needed

# Medium = 20K
mlpL:
  type: 'mlp'
  min_epochs: 30000
  hidden_layer: [110,110,110]
moeL:
  type: 'moe'
  min_epochs: 30000
  nex : 32
  expert_hidden_layer: [16,16,16]
  gate_hidden_layer: [64]