general:
  pe_num_freq                   : 4                             # Positional encoding number of frequencies (same as Neural Bounding)
  batch_size                    : 500000                        # Training
  learning_rate                 : 0.01                          # Training
  learning_rate_conservative    : 0.001                         # Learning rate that is switched to for neural methods once conservativness is enforced through asymmetric BCE
  loss_logging_frequency        : 100                           # Each N epoch we print and save the loss + other traininig metrics that we plot in a summary training plot
  boundary_threshold            : 0.5                           # Decision boundary when converting continous model output to binary 
  inf_bench_query_size          : 10000000                      # 10M, size of query to speed benchmark inference with
  infB_batch_size               : 500000                        # Batchsizes to test evaluate inference time -> 0 = inf_bench_query_size % infB_batch_size
  inf_bench_repitions           : 1000                          # Number of repitions to median speed benchmark 
  inf_benchmark                 : True                          # Flag for infernece benchmarking or not, as this takes much extra time to run without always being needed
  vis_results                   : True                          # Visualize results or not e.g. Create plots, extract VDBs or meshes
  gamma                         : {"S": 4, "M": 4, "L": 4}      # Increase focality for larger models to stabelize training and shorten training time


# Small = 500
mlpS:
  type                          : 'mlp'
  min_epochs                    : 5000
  hidden_layer                  : [13,13]
moegS:
  type                          : 'moeg'
  min_epochs                    : 5000
  grid_dim                      : 2
  expert_hidden_layer           : [2,2]
moeS:
  type                          : 'moe'
  min_epochs                    : 5000
  nex                           : 8
  expert_hidden_layer           : [2,2]
  gate_hidden_layer             : [2]


# Medium = 5K
mlpM:
  type                          : 'mlp'
  min_epochs                    : 10000
  hidden_layer                  : [45,45,45]
moegM:
  type                          : 'moeg'
  min_epochs                    : 10000
  grid_dim                      : 2
  expert_hidden_layer           : [8,8,8]
moeM:
  type                          : 'moe'
  min_epochs                    : 10000
  nex                           : 8
  expert_hidden_layer           : [8,8,8]
  gate_hidden_layer             : [8]


# Large = 20K
mlpL:
  type                          : 'mlp'
  min_epochs                    : 20000
  hidden_layer                  : [94,94,94]
moegL:
  type                          : 'moeg'
  min_epochs                    : 20000
  grid_dim                      : 3
  expert_hidden_layer           : [13,13,13]
moeL:
  type                          : 'moe'
  min_epochs                    : 20000
  nex                           : 27
  expert_hidden_layer           : [13,13,13]
  gate_hidden_layer             : [16]